### ISSUE TITLE
Feature request: "world"

### ISSUE THREAD

**Issue by aheckmann** [TooTallNate/r#1]
Right now this project is super awesome but i think it could be even better if it exported 'helloooo world' instead of just 'helloooo'.

**Comment by Qix-** [comment]
I think there's a typo, it's supposed to be `wooorld`.

**Comment by TooTallNate** [comment]
Hahaha. You guys are dope. This repo was just a demonstration of a canary -> stable branching/merging strategy that I proposed. I'm gonna delete this repo now.
